version: '3'

services:
  nginx:
    image: nginx
    container_name: nx-careerroad-rakusai-nginx
    volumes:
    - ./laravel:/var/www/html/nx-careerroad-rakusai
    - ./docker/app/000-default.conf:/etc/nginx/conf.d/default.conf
    tty: true
    ports:
    - "10082:80"
    - "443:443"
    depends_on:
    - app

  app:
    ports:
      - "9000:9000"
    build: ./docker/app
    container_name: nx-careerroad-rakusai-app
    # command: php artisan serve
    volumes:
      - ./laravel:/var/www/html/nx-careerroad-rakusai
    working_dir: /var/www/html/nx-careerroad-rakusai
    links:
      - db

  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    tty: true
    command: npm run dev
    volumes:
      - ./nextjs:/app
    ports:
      - "3000:3000"

  db:
    image: mysql:8.0
    container_name: nx-careerroad-rakusai-db
    environment:
      MYSQL_ROOT_PASSWORD: JYNTGXf5DZLYLfq6
      MYSQL_DATABASE: nx-careerroad-rakusai
      MYSQL_USER: nx-careerroad-rakusai
      MYSQL_PASSWORD: H{tb1Jp5
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3308:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: nx-careerroad-rakusai-phpmyadmin
    links:
        - db
    ports:
        - "8082:80"
    volumes:
        - ./docker/phpmyadmin/sessions:/sessions
